# Generated by Django 4.2.1 on 2023-05-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='media/profiles/default.png', upload_to='media/profiles/'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='user', verbose_name='Username'),
        ),
    ]
