# Generated by Django 4.2.1 on 2023-06-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_user_stripe_customer_id_user_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='has_active_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
