# Generated by Django 4.2.1 on 2023-06-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_company_has_active_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='has_active_subscription',
        ),
    ]
