# Generated by Django 4.2.1 on 2023-06-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_remove_company_has_active_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
