# Generated by Django 4.2.1 on 2023-06-23 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_company_end_date_paymenthistory_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='end_date',
            new_name='subscription_end_date',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='end_date',
        ),
    ]
