# Generated by Django 4.2.1 on 2023-05-26 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_alter_project_assign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audithistory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='audithistory',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='audithistory',
            name='action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
