# Generated by Django 4.2.1 on 2023-06-15 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0004_audithistory_is_deleted_project_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audithistory',
            name='user_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_form', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audithistory',
            name='user_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='audithistory',
            name='action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='action_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
