# Generated by Django 4.2.1 on 2023-06-23 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_attachment_end_date_audithistory_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='audithistory',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='end_date',
        ),
    ]
